### ISSUE TITLE
Reverse Landscape

### ISSUE THREAD

**Issue by iwelch** [ho-tex/pdflscape#1]
hi H---it would be very useful to add a 180-degree-rotated second landscape mode.  I am typesetting a book, and I need to show two graphs in landscape, one on recto and one on versa.  It's not great to ask the reader to rotate the book when looking at both pages, rather than see both figures in the same rotation.

**Comment by u-fischer** [comment]
Please always provide a small, complete example. 

Be aware that pdflscape only handles the rotating of the view in a PDF viewer, the rotating of the content on the page is done by lscape or the rotating package (which has the option figuresright to always rotate in the same direction).

**Comment by iwelch** [comment]
mea culpa.  I misunderstand what pdflscape does.
