### ISSUE TITLE
rotated page

### ISSUE THREAD

**Issue by hvoss49** [ho-tex/pdflscape#2]
The landscape page is rotated in the pdf for all engines. Using package `lscape` instead it is okay.
I cannot remember that this behaviour  was seen in the past.

```
\documentclass{article}
\usepackage{graphicx}
\usepackage{pdflscape}
%\usepackage{lscape}% works
\begin{document}
foo\newpage
\noindent
\rotatebox{90}{\rule{\textheight}{\textwidth}}%
\newpage 
bar
\begin{landscape}
\rule{\textheight}{\textwidth}
\end{landscape}

baz
\end{document}
```

**Comment by u-fischer** [comment]
Sorry I don't know what you mean. Yes, the landscape page is rotated in the viewer (the page number 4 is on the left) but that is the main point of pdflscape and has been like this since ever.

**Comment by hvoss49** [comment]
ok, then I am wrong ...
