### ISSUE TITLE
Image rotation is not consistent.

### ISSUE THREAD

**Issue by piiskop** [ho-tex/pdflscape#3]
```
\documentclass{book}
\usepackage{pdflscape}
\begin{document}
	\begin{landscape}
	Lahendame ülesanded 1-5.
	\begin{figure}
		\centering
		\includegraphics{/home/kalmer/test/rmd/baasreeglistik/g.pdf}
		\caption{\label{fig:cities}joppenpuhh}
	\end{figure}
        \end{landscape}
\end{document}

```
[g.pdf](https://github.com/ho-tex/pdflscape/files/14741664/g.pdf)

I expect both the text and the image with its caption to appear on the same landscape page as there is enough space for all of it. However, the text is placed on a separate page and the image is rotated making it not fit the page.

**Comment by u-fischer** [comment]
Well LaTeX doesn't agree with your expectation:

~~~~
LaTeX Warning: Float too large for page by 39.28981pt on input line 186
~~~~

Also floats like figure can float away.  

This is not an issue with pdflscape but with your code. Ask on a general support side how to correctly code your figure.
